export interface ArchiveItem {
  id: number;
  title: string;
  category: string;
  source: string;
  tags: string[];
  description: string;
  views: number;
  createdAt: string;
}

export const initialArchiveItems: ArchiveItem[] = [
  {
    id: 1,
    title: 'Frontoplastia - Paciente de 43 anos com cuello pesado',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério Brandao - WhatsApp',
    tags: ['Caso Clínico', 'Frontoplastia', 'Deep Neck'],
    description: 'Caso de paciente de 43 anos com cuello pesado. Plan quirúrgico: frontoplastia, párpados superiores, endomediofacial, cuello profundo con extracción de grasa supraplatismal con bisturí eléctrico y por debajo del platisma, rasurado y plicatura del digástrico. Técnica de sutura desde el ángulo del cuello hasta la mastoides con Vicryl 2.0. Injertos de grasa en el mentón y los labios. En la nariz, solo realicé la punta, los cartílagos alares y la domus.',
    views: 1250,
    createdAt: '2025-06-27T12:36:33Z',
  },
  {
    id: 2,
    title: 'Técnicas Individualizadas de Frontoplastia - Acesso Lateral',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério Brandao - Discussão Técnica',
    tags: ['Frontoplastia', 'Técnica Cirúrgica', 'Discussão'],
    description: 'Discussão sobre a importância de aprender múltiplas técnicas para individualizar a estratégia de tratamento. Técnica: acesso lateral da frontoplastia para elevar apenas a região temporal e compensar a tração superior da pele do terço médio. Sem descolamento central para não elevar a glabela. Pálpebras superiores apenas pele, mantendo músculo e bolsas. Plicatura tipo Baker e Crevassi lateral. PLATISMOTOMIA abaixo da sutura cerca de 2cm para cada lado.',
    views: 890,
    createdAt: '2025-05-18T13:10:21Z',
  },
  {
    id: 3,
    title: 'Revisão Pré-Operatória de Browlift',
    category: 'Discussões de Casos',
    source: 'Dra. Suhira & Dr. Khaled Bazzi',
    tags: ['Browlift', 'Revisão', 'Preparação'],
    description: 'Discussão sobre a importância de revisar as aulas antes das cirurgias. Dr. Khaled Bazzi menciona ter um caso para operar e a necessidade de rever a aula antes da cirurgia. Dra. Suhira confirma o uso das aulas do browlift no Hotmart para revisar antes dos procedimentos.',
    views: 650,
    createdAt: '2024-08-20T06:34:52Z',
  },
  {
    id: 4,
    title: 'Anatomia Aplicada e Técnica de Frontoplastia',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério - Curso',
    tags: ['Anatomia', 'Frontoplastia', 'Endomidface'],
    description: 'Liberação da aula de anatomia aplicada e primeira técnica de frontoplastia. Discussão sobre o famoso endomidface que o Dr. Kao projetou como Ponytail Facelift. Possibilidade de fazer fronto e terço médio em pacientes com flacidez moderada. Excelente opção para refinamento de resultados de blefaroplastias e liftings faciais.',
    views: 1567,
    createdAt: '2024-03-18T15:23:44Z',
  },
  {
    id: 5,
    title: 'Facelift em Pacientes Jovens - Técnica com Plicatura',
    category: 'Discussões de Casos',
    source: 'Dr. Robério Brandao, Dra. Suhira, Dr. Marcos Pelosi',
    tags: ['Facelift', 'Paciente Jovem', 'Plicatura'],
    description: 'Discussão sobre o aumento de pacientes jovens buscando facelift. Técnica associada à plicatura pode ser usada em casos avançados com menos dificuldade técnica e riscos do deep plane. Uso de dreno apenas quando descola o terço médio todo, retirado na saída do hospital. Discussão sobre tempo cirúrgico e uso de sonda vesical.',
    views: 780,
    createdAt: '2024-05-28T20:03:41Z',
  },
  {
    id: 6,
    title: 'Primeiro Caso de Browlift - Orientações',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Gilvan & Dr. Robério Brandao',
    tags: ['Browlift', 'Primeira Cirurgia', 'Curativo'],
    description: 'Discussão sobre como selecionar o melhor paciente para o primeiro caso de browlift. Dr. Gilvan questiona sobre iniciar fazendo somente o BL e qual seria o melhor paciente para selecionar como primeiro caso. Também aborda dúvidas sobre o curativo no BL e se precisa fazer o capacete.',
    views: 420,
    createdAt: '2024-10-22T11:38:00Z',
  },
  {
    id: 7,
    title: 'Técnica de Suleiman Tas - Deep Plane Modificado',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério Brandao & Dr. Karim',
    tags: ['Deep Plane', 'Técnica Internacional', 'Prolene'],
    description: 'Cirurgia realizada ao vivo no Brasil durante congresso pelo cirurgião Suleiman Tas da Turquia. Técnica que separa o terço médio pelo plano profundo através do acesso temporal, passando vários fios de Prolene 2.0 e fixando-os na fáscia temporal profunda. Discussão sobre resultados espetaculares e cursos caríssimos na Turquia.',
    views: 980,
    createdAt: '2024-11-22T18:34:29Z',
  },
  {
    id: 8,
    title: 'Frontoplastia vs Transplante - Caso de Fronte Alta',
    category: 'Discussões de Casos',
    source: 'Dra. Jacqueline Presotto & Dr. Robério Brandao',
    tags: ['Frontoplastia', 'Transplante', 'Feminilização'],
    description: 'Discussão sobre melhor indicação para paciente com fronte alta após esgotar tratamentos clínicos. Necessidade de reduzir o comprimento da fronte semelhante a uma feminilização. Técnica excelente para o terço superior e parte superior do terço médio, ajudando em qualquer situação de rejuvenescimento facial. Importância de documentar pacientes em vídeo.',
    views: 670,
    createdAt: '2024-05-21T17:09:48Z',
  },
  {
    id: 9,
    title: 'Complicação Pós Deep Plane - Xerostomia e Dormência',
    category: 'Complicações',
    source: 'Dra. Deyse Oliveira & Dra. Vanesa Barquero',
    tags: ['Deep Plane', 'Complicações', 'Xerostomia'],
    description: 'Caso de paciente que há 10 meses fez cirurgia de lifting com deep plane em outro serviço. Apresenta queixa de xerostomia, dormência no lábio inferior e leve abaulamento submandibular esquerdo. Ultrassom mostrou pequeno cisto coloide na tireoide. Discussão sobre conduta adequada.',
    views: 890,
    createdAt: '2024-05-30T19:16:13Z',
  },
  {
    id: 10,
    title: 'Potencial da Técnica - Casos da Semana',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério Brandao',
    tags: ['Resultados', 'Casos Práticos', 'Técnica'],
    description: 'Apresentação de casos da semana para demonstrar o potencial da técnica. Curso com design começando com aulas de anatomia básica e conceitos fundamentais. Após os primeiros 3 módulos, classe interativa ao vivo. Disponibilidade constante no grupo de WhatsApp para perguntas e possíveis dificuldades.',
    views: 1120,
    createdAt: '2024-08-01T19:05:00Z',
  },
  {
    id: 11,
    title: 'Enxerto de Gordura em Pálpebras Superiores',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Robério Brandao & Dr. Nilton',
    tags: ['Lipoenxertia', 'Pálpebras', 'Nanofat'],
    description: 'Discussão sobre enxerto de gordura em pérolas ou Nanofat na pálpebra superior para pacientes com olhos encovados. Casos apresentados onde foi realizado enxerto nas pálpebras superiores para ajudar a rebaixar o sulco palpebral, combinado com mullerectomia.',
    views: 560,
    createdAt: '2025-05-18T13:25:14Z',
  },
  {
    id: 12,
    title: 'Técnica de Serdev - Limitações e Durabilidade',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Karim',
    tags: ['Serdev', 'Mínimo Abordaje', 'Durabilidade'],
    description: 'Análise da técnica de Serdev e suas limitações. Necessidade de selecionar muito bem o paciente indicado. Resultado satisfatório mas com duração limitada de máximo 12-18 meses devido ao fio reabsorvível. Discussão sobre paixão pela cirurgia facial e técnicas de mínima abordagem.',
    views: 340,
    createdAt: '2024-11-22T19:28:46Z',
  },
  {
    id: 13,
    title: 'Diprospan e Melhora em Problemas Articulares',
    category: 'Discussões de Casos',
    source: 'Dr. Marcos Estephan Gobbo',
    tags: ['Medicação', 'Caso Clínico', 'Resultado'],
    description: 'Relato de caso onde paciente apresentou melhora quando fez uso de Diprospan para um problema articular. Discussão sobre efeitos sistêmicos e benefícios secundários em procedimentos estéticos.',
    views: 220,
    createdAt: '2025-05-18T16:07:28Z',
  },
  {
    id: 14,
    title: 'Resultados Fantásticos - Congresso Internacional Rio',
    category: 'Eventos',
    source: 'Dra. Jacqueline Presotto',
    tags: ['Congresso', 'Resultados', 'Internacional'],
    description: 'Relato sobre o Congresso Internacional de Cirurgia de Face no Rio de Janeiro. Apresentação de resultados fantásticos em frontoplastia e outras técnicas de rejuvenescimento facial. Troca de experiências entre cirurgiões internacionais.',
    views: 780,
    createdAt: '2024-05-21T18:52:10Z',
  },
  {
    id: 15,
    title: 'Pacientes Jovens - Alternativa aos Preenchimentos',
    category: 'Discussões de Casos',
    source: 'Dra. Suhira',
    tags: ['Paciente Jovem', 'Preenchimento', 'Bioestímulos'],
    description: 'Discussão sobre o aumento de pacientes jovens que não querem ficar reféns de muitos preenchimentos, bioestímulos e tecnologias faciais. Busca por soluções cirúrgicas definitivas em idade mais precoce. Necessidade de segurança cirúrgica para estes casos.',
    views: 890,
    createdAt: '2024-05-28T20:07:09Z',
  },
  {
    id: 16,
    title: 'Alergia a Sulfas - Consideração Importante',
    category: 'Pós-Operatório',
    source: 'Dr. Robério Brandao',
    tags: ['Alergia', 'Sulfas', 'Segurança'],
    description: 'Alerta sobre a importância de verificar se o paciente não é alérgico a sulfas antes de procedimentos. Consideração fundamental para segurança do paciente e escolha de medicações no peri e pós-operatório.',
    views: 420,
    createdAt: '2024-05-28T20:17:08Z',
  },
  {
    id: 17,
    title: 'Descolamento de Pele Cervical - Técnica Detalhada',
    category: 'Técnicas Cirúrgicas',
    source: 'Dr. Marcos Pelosi & Dr. Robério Brandao',
    tags: ['Cervical', 'Descolamento', 'Técnica'],
    description: 'Discussão sobre o descolamento de toda a pele da região submandibular versus apenas região central e lateral. Caso específico de paciente de 72 anos. Técnica de descolamento de toda a pele cervical pelo acesso lateral e submento, sem descolar acima da mandíbula.',
    views: 560,
    createdAt: '2024-05-28T20:28:48Z',
  },
  {
    id: 18,
    title: 'Lesão do Ramo Frontal - Complicação',
    category: 'Complicações',
    source: 'Dr. Robério Brandao',
    tags: ['Complicação', 'Nervo Frontal', 'Zigoma'],
    description: 'Caso de lesão do ramo frontal esquerdo durante procedimento. Discussão sobre como a mudança de plano sobre o zigoma pode facilitar o procedimento mas também aumentar riscos. Importância da anatomia e técnica cuidadosa.',
    views: 670,
    createdAt: '2024-11-22T18:34:29Z',
  },
  {
    id: 19,
    title: 'Cursos Caríssimos na Turquia - Análise de Mercado',
    category: 'Educação',
    source: 'Dr. Karim',
    tags: ['Cursos', 'Turquia', 'Mercado'],
    description: 'Discussão sobre cirurgiões que publicam resultados espetaculares no TikTok e organizam cursos muito caros na Turquia, cobrando mais de 6000 dólares pela visita à clínica. Análise crítica do mercado de educação em cirurgia plástica.',
    views: 340,
    createdAt: '2024-11-22T19:25:44Z',
  },
  {
    id: 20,
    title: 'Documentação em Vídeo - Evolução dos Pacientes',
    category: 'Documentação',
    source: 'Dr. Robério Brandao',
    tags: ['Vídeo', 'Documentação', 'Evolução'],
    description: 'Importância de documentar sempre os pacientes em vídeo para acompanhar a evolução. Fica mais interessante e educativo para ver o progresso ao longo do tempo. Ferramenta essencial para análise de resultados e apresentações.',
    views: 890,
    createdAt: '2024-05-21T18:49:02Z',
  }
];

export const categoryColors: { [key: string]: string } = {
  'Discussões de Casos': 'text-cyan-400 border-cyan-400/30 bg-cyan-500/10',
  'Técnicas Cirúrgicas': 'text-green-400 border-green-400/30 bg-green-500/10',
  'Pós-Operatório': 'text-blue-400 border-blue-400/30 bg-blue-500/10',
  'Instrumentais': 'text-purple-400 border-purple-400/30 bg-purple-500/10',
  'Complicações': 'text-red-400 border-red-400/30 bg-red-500/10',
  'Documentação': 'text-indigo-400 border-indigo-400/30 bg-indigo-500/10',
  'Eventos': 'text-yellow-400 border-yellow-400/30 bg-yellow-500/10',
  'Educação': 'text-pink-400 border-pink-400/30 bg-pink-500/10',
  'Outros': 'text-gray-400 border-gray-400/30 bg-gray-500/10',
};

export const tagColors: { [key: string]: string } = {
  'Caso Clínico': 'text-red-300 border-red-400/30 bg-red-500/10',
  'Vídeo': 'text-blue-300 border-blue-400/30 bg-blue-500/10',
  'PDF': 'text-green-300 border-green-400/30 bg-green-500/10',
  'Discussão': 'text-purple-300 border-purple-400/30 bg-purple-500/10',
  'Frontoplastia': 'text-yellow-300 border-yellow-400/30 bg-yellow-500/10',
  'Deep Neck': 'text-cyan-300 border-cyan-400/30 bg-cyan-500/10',
  'Deep Plane': 'text-indigo-300 border-indigo-400/30 bg-indigo-500/10',
  'Browlift': 'text-pink-300 border-pink-400/30 bg-pink-500/10',
  'Facelift': 'text-orange-300 border-orange-400/30 bg-orange-500/10',
  'Anatomia': 'text-teal-300 border-teal-400/30 bg-teal-500/10',
  'Endomidface': 'text-lime-300 border-lime-400/30 bg-lime-500/10',
  'Plicatura': 'text-amber-300 border-amber-400/30 bg-amber-500/10',
  'Primeira Cirurgia': 'text-rose-300 border-rose-400/30 bg-rose-500/10',
  'Curativo': 'text-emerald-300 border-emerald-400/30 bg-emerald-500/10',
  'Técnica Internacional': 'text-violet-300 border-violet-400/30 bg-violet-500/10',
  'Prolene': 'text-gray-300 border-gray-400/30 bg-gray-500/10',
  'Transplante': 'text-stone-300 border-stone-400/30 bg-stone-500/10',
  'Feminilização': 'text-sky-300 border-sky-400/30 bg-sky-500/10',
  'Complicações': 'text-red-300 border-red-400/30 bg-red-500/10',
  'Xerostomia': 'text-fuchsia-300 border-fuchsia-400/30 bg-fuchsia-500/10',
  'Resultados': 'text-green-300 border-green-400/30 bg-green-500/10',
  'Casos Práticos': 'text-blue-300 border-blue-400/30 bg-blue-500/10',
  'Técnica': 'text-purple-300 border-purple-400/30 bg-purple-500/10',
  'Lipoenxertia': 'text-orange-300 border-orange-400/30 bg-orange-500/10',
  'Pálpebras': 'text-cyan-300 border-cyan-400/30 bg-cyan-500/10',
  'Nanofat': 'text-indigo-300 border-indigo-400/30 bg-indigo-500/10',
  'Serdev': 'text-yellow-300 border-yellow-400/30 bg-yellow-500/10',
  'Mínimo Abordaje': 'text-pink-300 border-pink-400/30 bg-pink-500/10',
  'Durabilidade': 'text-teal-300 border-teal-400/30 bg-teal-500/10',
  'Medicação': 'text-lime-300 border-lime-400/30 bg-lime-500/10',
  'Resultado': 'text-amber-300 border-amber-400/30 bg-amber-500/10',
  'Congresso': 'text-rose-300 border-rose-400/30 bg-rose-500/10',
  'Internacional': 'text-emerald-300 border-emerald-400/30 bg-emerald-500/10',
  'Paciente Jovem': 'text-violet-300 border-violet-400/30 bg-violet-500/10',
  'Preenchimento': 'text-gray-300 border-gray-400/30 bg-gray-500/10',
  'Bioestímulos': 'text-stone-300 border-stone-400/30 bg-stone-500/10',
  'Alergia': 'text-red-300 border-red-400/30 bg-red-500/10',
  'Sulfas': 'text-sky-300 border-sky-400/30 bg-sky-500/10',
  'Segurança': 'text-green-300 border-green-400/30 bg-green-500/10',
  'Cervical': 'text-blue-300 border-blue-400/30 bg-blue-500/10',
  'Descolamento': 'text-purple-300 border-purple-400/30 bg-purple-500/10',
  'Complicação': 'text-red-300 border-red-400/30 bg-red-500/10',
  'Nervo Frontal': 'text-orange-300 border-orange-400/30 bg-orange-500/10',
  'Zigoma': 'text-cyan-300 border-cyan-400/30 bg-cyan-500/10',
  'Cursos': 'text-indigo-300 border-indigo-400/30 bg-indigo-500/10',
  'Turquia': 'text-yellow-300 border-yellow-400/30 bg-yellow-500/10',
  'Mercado': 'text-pink-300 border-pink-400/30 bg-pink-500/10',
  'Documentação': 'text-teal-300 border-teal-400/30 bg-teal-500/10',
  'Evolução': 'text-lime-300 border-lime-400/30 bg-lime-500/10',
  'Revisão': 'text-amber-300 border-amber-400/30 bg-amber-500/10',
  'Preparação': 'text-rose-300 border-rose-400/30 bg-rose-500/10',
};